### ISSUE TITLE
Name is confusing

### ISSUE THREAD

**Issue by BytesOfMan** [doged-io/doged#82]
"dogecash" sounds like a new token (pretty sure there already is an existing dogecash token, if not many). Important for name to unambiguously indicate this software product is for Dogecoin ($DOGE).

It's probably not possible for the name to do this perfectly. Will probably need some kind of tagline that is also regularly featured, e.g. "<NewName> - An <optimized/faster/distinguished/somhow-improved> full node implementation for Dogecoin"

**Comment by EyeOfPython** [comment]
Good point. We'll poll people for a good rebrand
